from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK_PAIRS = (
    (ROOT / "requirements.in", ROOT / "requirements.txt"),
    (ROOT / "requirements-dev.in", ROOT / "requirements-dev.txt"),
    (ROOT / "requirements-audit.in", ROOT / "requirements-audit.txt"),
)
REQUIREMENT_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9_.-]+)(?:\[[^]]+\])?==(?P<version>[^;\s]+)(?:\s*;\s*(?P<marker>.+))?$"
)


def normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_direct_requirements(path: Path) -> list[tuple[str, str, str | None]]:
    requirements: list[tuple[str, str, str | None]] = []
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("-r "):
            continue
        match = REQUIREMENT_RE.fullmatch(line)
        if not match:
            raise ValueError(f"{path.name}:{line_number}: direct dependency must use an exact == pin")
        requirements.append(
            (
                normalize_name(match.group("name")),
                match.group("version"),
                match.group("marker"),
            )
        )
    return requirements


def parse_lock(path: Path) -> dict[str, tuple[str, str | None]]:
    content = path.read_text(encoding="utf-8")
    if "This file is autogenerated by pip-compile" not in content:
        raise ValueError(f"{path.name}: missing pip-compile generated header")
    if "--no-index" in content:
        raise ValueError(f"{path.name}: generated command must not force offline --no-index installs")

    requirements: dict[str, tuple[str, str | None]] = {}
    for raw_line in content.splitlines():
        match = REQUIREMENT_RE.fullmatch(raw_line.strip())
        if match:
            requirements[normalize_name(match.group("name"))] = (
                match.group("version"),
                match.group("marker"),
            )
    return requirements


def main() -> int:
    errors: list[str] = []
    for input_path, lock_path in LOCK_PAIRS:
        try:
            direct_requirements = parse_direct_requirements(input_path)
            locked_requirements = parse_lock(lock_path)
        except ValueError as exc:
            errors.append(str(exc))
            continue

        for name, expected_version, expected_marker in direct_requirements:
            locked = locked_requirements.get(name)
            if locked is None:
                errors.append(f"{lock_path.name}: missing direct dependency {name}=={expected_version}")
                continue
            locked_version, locked_marker = locked
            if locked_version != expected_version:
                errors.append(
                    f"{lock_path.name}: {name} is {locked_version}, expected {expected_version} from {input_path.name}"
                )
            if expected_marker and locked_marker != expected_marker:
                errors.append(f"{lock_path.name}: {name} marker {locked_marker!r}, expected {expected_marker!r}")

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    print("OK: Python dependency inputs and generated locks are aligned")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
